### ISSUE TITLE
Attribute namespaces not supported "natively"

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [rundeck-plugins/rundeck-json-plugin#2]
It would make sense to support defining attribute namespaces as objects:

```
{
"test": {
 "attr1": "a",
  "attr2": "b",
  "attr3": "c"
 }
}
```

The current implementation supports namespaces only by using a colon in the property name:

```
{
  "test:attr1": "a",
  "test:attr2": "b",
  "test:attr3": "c"
}
```

Maybe this is already implemented in Rundeck's native JSON resource implementation (Version 2.6.)?

**Comment by gschueler** [comment]
good idea, it would make it nicer.  can you file an feature request on the rundeck project?  this plugin is not going to be updated as we have incorporated it in 2.6 like you mention

**Comment by natlibfi-arlehiko** [comment]
Done: rundeck/rundeck#1418
